spring:
  application:
    name: STUDENT-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/learning_application_student
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  config:
    import: configserver:http://localhost:8080

server:
  port: 8082